[target.riscv64gc-unknown-none-elf]
# Fragile hack!
# Use --image-base to set the virtual addresses for the ELF file.
# MercurOS Maia loads the kernel into physical memory according to the given virtual addresses.
# QEMU:
rustflags = ["-Clink-arg=--image-base=0x80020000"]
# Freedom Unmatched:
#rustflags = ["-Clink-arg=--image-base=0x87F0A000"]

[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
